# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev7+gfe39c0a.d20230925'  # type: str
__version_tuple__ = version_tuple = (0, 1, 'dev7', 'gfe39c0a.d20230925')  # type: tuple[int | str, ...]
